################################################################################
MLI_FILE		= cordova_background_fetch.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-background-fetch
################################################################################
